import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createGame,defaultBuild,hero,team,competition,allGames,overall,simulate,startMatch,stepMatch,finalizeMatch,next,upgrade,upgradeCost,validate,enterDraft,sign,requestTrade,decide} from '../dist/engine.js';
import {LEAGUES} from '../dist/leagues.js';
import {KEYS} from '../dist/config.js';
import {parseSave} from '../dist/storage.js';
const make=path=>createGame({...defaultBuild(),path:path||'young'});
function year(s){let y=s.season,n=0;while(s.season===y&&n++<500){assert.equal(s.pending,null);next(s,{interactive:false})}assert.equal(s.season,y+1);validate(s);return n}
test('calendriers réels, 41 réceptions NBA, effectifs partagés et absence de doublons quotidiens',()=>{
 let s=make(),seen=new Set();validate(s);
 for(let def of LEAGUES){let c=competition(s,def.id);for(let id of Object.keys(c.records)){assert.equal(c.schedule.filter(g=>g.home===id||g.away===id).length,def.games);if(def.id==='nba')assert.equal(c.schedule.filter(g=>g.home===id).length,41)}}
 for(let g of allGames(s))for(let id of [g.home,g.away]){let key=id+':'+g.day;assert.ok(!seen.has(key),key);seen.add(key)}
 assert.ok(s.teams.some(t=>t.competitions.includes('euroleague')&&t.competitions.length>1));assert.equal(new Set(s.teams.flatMap(t=>t.roster)).size,s.teams.length*10);
});
test('feuilles de match cohérentes en 32, 40 et 48 minutes ; aucune double application',()=>{
 for(let id of ['highschool','ncaa','nba']){let s=make(),g=competition(s,id).schedule[0],m=simulate(s,g);for(let [i,tid] of [g.home,g.away].entries()){let rows=team(s,tid).roster.map(id=>g.result.box[id]);assert.equal(rows.reduce((n,b)=>n+b.pts,0),m.score[i]);assert.ok(Math.abs(rows.reduce((n,b)=>n+b.min,0)-(m.duration*5+m.ot*25))<1e-6);for(let b of rows)assert.equal(b.pts,2*b.fgm+b.tpm+b.ftm)}assert.equal(finalizeMatch(s,g,m),false)}
});
test('moteur déterministe et sauvegarde en cours de match',()=>{let s=make(),g=s.schedule[0],m=startMatch(s,g);stepMatch(s,m,83);s.match=m;let restored=parseSave(JSON.stringify(s));stepMatch(s,m,10000);stepMatch(restored,restored.match,10000);assert.deepEqual(m,restored.match);assert.deepEqual(s.rng,restored.rng)});
test('progression manuelle, plafonds et imports invalides',()=>{let s=make(),p=hero(s),v=p.attrs.three,c=upgradeCost(p,'three');assert.ok(upgrade(s,'three'));assert.equal(p.attrs.three,v+1);assert.equal(s.points,18-c);p.attrs.three=p.caps.three;assert.equal(upgrade(s,'three'),false);for(let input of ['null','{}','bad','{"schema":9}'])assert.throws(()=>parseSave(input));let bad=structuredClone(s);bad.players[0].attrs.three=1000;assert.throws(()=>validate(bad));assert.deepEqual(parseSave(JSON.stringify(s)),s)});
test('migration V1 conserve joueur, points et ancien match dans les archives',()=>{let old=JSON.parse(fs.readFileSync(new URL('./fixtures/v1-in-progress.json',import.meta.url))),s=parseSave(JSON.stringify(old)),p=old.players.find(p=>p.id===old.hero);assert.equal(s.schema,3);assert.deepEqual(hero(s).attrs,p.attrs);assert.equal(s.points,old.points);assert.deepEqual(s.legacyArchive.match,old.match);assert.equal(s.season,old.season+1);validate(s)});
test('transfert international conserve le profil, les résultats et les effectifs',()=>{let s=make('rookie');hero(s).contract.years=1;let g=s.schedule[0];simulate(s,g);let result=structuredClone(g.result),attrs=structuredClone(hero(s).attrs);assert.ok(requestTrade(s));let i=s.offers.findIndex(o=>s.teams.find(t=>t.id===o.team).league!=='nba');assert.ok(i>=0);assert.ok(sign(s,i));assert.notEqual(s.league,'nba');assert.deepEqual(hero(s).attrs,attrs);assert.deepEqual(g.result,result);validate(s);assert.equal(s.teams.flatMap(t=>t.roster).filter(id=>id==='hero').length,1)});
test('draft : une franchise détient le choix ; non-drafté reçoit des offres étrangères',()=>{for(let score of [100,20]){let s=make('prospect');hero(s).age=19;s.career.collegeYears=1;s.lastSeasonScouting={score,projection:'Test'};assert.ok(enterDraft(s));let nba=s.offers.filter(o=>s.teams.find(t=>t.id===o.team).league==='nba');assert.equal(nba.length,score===100?1:0);assert.ok(s.offers.length);assert.equal(enterDraft(s),false);assert.ok(sign(s,0));assert.equal(s.career.stage,'pro');validate(s)}});
test('trois saisons complètes : lycée, recrutement universitaire, progression puis choix de draft',()=>{let s=make(),before=overall(hero(s));let steps=year(s);assert.ok(overall(hero(s))>=before+5);assert.equal(hero(s).age,17);assert.equal(s.pending,null);steps+=year(s);assert.equal(hero(s).age,18);assert.ok(s.offers.every(o=>o.academic));assert.ok(sign(s,0));assert.equal(s.league,'ncaa');steps+=year(s);assert.equal(s.pending.type,'draft-choice');assert.equal(s.career.collegeYears,1);let copy=structuredClone(s);assert.ok(decide(copy,'stay'));assert.notEqual(copy.phase,'Orientation');assert.ok(decide(s,'draft'));assert.ok(sign(s,0));assert.equal(s.career.stage,'pro');assert.ok(s.archives.every(a=>a.competitions.every(c=>c.champion&&c.games.every(g=>g.score))));for(let k of KEYS)assert.ok(hero(s).attrs[k]<=hero(s).caps[k]);validate(s);console.log('PARCOURS',JSON.stringify({seasons:3,steps,initial:before,overall:overall(hero(s)),draft:s.draftResult.rank,league:s.league}))});
