import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright-core';import {VERSION} from '../dist/config.js';
const root=new URL('../dist/',import.meta.url).pathname,output=new URL('../test-results/',import.meta.url).pathname;fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(4179,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4179/?v='+VERSION);await page.waitForSelector('[data-action="next-step"]');await page.evaluate(async v=>{const {createGame,defaultBuild}=await import('./engine.js?v='+v);await(await import('./storage.js?v='+v)).save(createGame({...defaultBuild(),path:'rookie'}));},VERSION);
 await page.reload();await page.waitForSelector('#advance-size');const nav=()=>page.locator('[data-action="tab:career"]:visible').first().click(),load=()=>page.evaluate(async v=>(await(await import('./storage.js?v='+v)).load()),VERSION);await nav();
 const talk=async(topic,count)=>{await page.locator(`[data-action="talk:${topic}"]`).click();await page.waitForFunction(n=>document.querySelector('.discussions summary')?.textContent.endsWith('· '+n),count);};const before=await load();
 await talk('coach-plan',1);assert.equal(await page.locator('[data-action="talk:coach-plan"]').isDisabled(),true);assert.match(await page.locator('.discussions').innerText(),/concurrence au poste/);
 await talk('agent-title',2);assert.equal((await load()).careerPlan.preference,'title');assert.equal(await page.locator('[data-action="talk:agent-salary"]').isDisabled(),true);
 await talk('team-work',3);let s=await load();assert.ok(s.careerPlan.discussions.teamwork);assert.equal(s.day,before.day);assert.deepEqual(s.rng,before.rng);assert.equal(await page.locator('[data-action="talk:team-work"]').isDisabled(),true);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('.discussions').screenshot({path:output+`v36-discussions-${width}.png`});}
 await page.reload();await page.waitForSelector('#advance-size');await nav();assert.ok((await load()).careerPlan.discussions.teamwork);assert.equal(await page.locator('[data-action="talk:agent-salary"]').isDisabled(),true);
 await page.locator('summary').filter({hasText:'Entraînement, rôle et contrat'}).click();await page.locator('#activity').selectOption('video');assert.equal((await load()).activity,'video');
 await page.locator('[data-action="tab:home"]:visible').first().click();await page.locator('#advance-size').selectOption('2');await page.locator('[data-action="advance"]:visible').first().click();await page.waitForFunction(()=>{const b=document.querySelector('[data-action="advance"]');return b&&!b.disabled;});s=await load();assert.ok(s.day>before.day);assert.ok(s.careerPlan.discussions.teamwork.videoDays>0);assert.equal(s.careerPlan.preference,'title');
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.waitForSelector('#advance-size');await nav();assert.ok((await page.locator('.discussions').innerText()).includes(s.careerPlan.discussions.teamwork.person));await context.setOffline(false);
 await page.evaluate(async v=>{const store=await import('./storage.js?v='+v),s=await store.load();s.pending={type:'sport',title:'Test',text:'Décision en cours',choices:[['accept','Continuer']]};await store.save(s);},VERSION);await page.reload();await page.waitForSelector('#advance-size');await nav();assert.equal(await page.locator('.discussions [data-action^="talk:"]:not([disabled])').count(),0);
 assert.deepEqual(errors,[]);const result={engine:VERSION,errors,widths:[320,390,1440],coachReply:true,agentPriority:true,teamCommitment:true,cooldowns:true,noHiddenDayOrRng:true,workerFollowup:true,reload:true,offline:true,pendingGuard:true};fs.writeFileSync(output+'v36-browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();await new Promise(r=>server.close(r));}
