import crypto from 'node:crypto';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright-core';import {VERSION} from '../dist/config.js';
const root=path.resolve(process.env.QA_ROOT||new URL('../dist/',import.meta.url).pathname),output=new URL('../test-results/',import.meta.url).pathname;fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
await new Promise(r=>server.listen(4180,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 await page.goto('http://127.0.0.1:4180/?v='+VERSION);await page.waitForSelector('[data-action="next-step"]');
 await page.evaluate(async v=>{const {createGame,defaultBuild}=await import('./engine.js?v='+v),s=createGame({...defaultBuild(),path:'rookie'});s.money=10000;s.life.policies={routine:'family',media:'team',agent:'local'};await(await import('./storage.js?v='+v)).save(s);},VERSION);
 const load=()=>page.evaluate(async v=>(await(await import('./storage.js?v='+v)).load()),VERSION),nav=tab=>page.locator(`[data-action="tab:${tab}"]:visible`).first().click();
 await page.reload();await page.waitForSelector('#advance-size');await nav('career');await page.waitForSelector('.collective-panel');const before=await load();
 const ids=before.teams.find(t=>t.id===before.team).roster.filter(id=>id!==before.hero).slice(0,2);
 await page.locator('#collective-partner-0').selectOption(ids[0]);await page.locator('#collective-partner-1').selectOption(ids[1]);await page.locator('[data-action="collective-routine:partners"]').click();assert.deepEqual((await load()).collective.partners,ids);
 await page.locator('[data-action="collective-open:stages"]').click();assert.equal(await page.locator('#stages-panel').evaluate(e=>e===document.activeElement),true);
 await page.locator('[data-action="stage-quote:video"]').click();await page.locator('[data-action="stage-dismiss"]').click();assert.equal((await load()).money,before.money);
 await page.locator('[data-action="stage-quote:video"]').click();
 await page.locator('[data-action="coach-finance"]').click();await page.locator('#finance-reserve').selectOption('0');
 await page.locator('[data-action="stage-confirm"]').click();assert.equal((await load()).money,before.money);assert.match(await page.locator('main').innerText(),/conditions ont changé/);
 await page.locator('[data-action="stage-confirm"]').click();let s=await load();assert.equal(s.money,9400);assert.equal(s.collective.stage.start,1);assert.equal(s.collective.stage.sessions,0);assert.deepEqual(s.rng,before.rng);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});for(const tab of ['life','career']){await nav(tab);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator(tab==='life'?'.stages-panel':'.collective-panel').screenshot({path:output+`v38-${tab}-${width}.png`});}}
 await nav('home');await page.locator('#advance-size').selectOption('2');await page.locator('[data-action="advance"]:visible').first().click();await page.waitForFunction(()=>{const b=document.querySelector('[data-action="advance"]');return b&&!b.disabled;});s=await load();assert.ok(s.collective.stage.sessions>0);assert.ok(s.collective.stage.mastery>0);
 await page.reload();await page.waitForSelector('#advance-size');assert.deepEqual((await load()).collective,s.collective);await nav('life');await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.waitForSelector('#advance-size');await nav('career');await page.waitForSelector('.collective-panel');await context.setOffline(false);
 // Import a different career while a quote is open: no quote or partners may leak.
 const replacement=await page.evaluate(async v=>{const e=await import('./engine.js?v='+v),x=e.createGame({...e.defaultBuild(),path:'rookie',name:'Autre carrière'});x.money=10000;return x;},VERSION);
 await nav('more');await page.locator('#import').setInputFiles({name:'other.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(replacement))});await page.waitForFunction(()=>document.body.innerText.includes('Autre carrière'));await nav('life');await page.locator('[data-action="stage-quote:video"]').click();await nav('more');await page.locator('#import').setInputFiles({name:'other.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(replacement))});await nav('life');assert.equal(await page.locator('.stage-quote').count(),0);
 const simulation=await page.evaluate(async v=>{
  const engine=await import('./engine.js?v='+v),collective=await import('./collective.js?v='+v),sim=await import('./simulation.js?v='+v),sport=await import('./sport-events.js?v='+v),commands=await import('./commands.js?v='+v);
  const s=engine.createGame({...engine.defaultBuild(),path:'rookie',seed:2026});s.money=10000;collective.bookStage(s,collective.stageQuote(s,'video'));sim.setAdvanceMode(s,'40');sim.beginAdvance(s);
  const direct=structuredClone(s),worker=new Worker('./worker.js?v='+v,{type:'module'});
  const output=new Promise((resolve,reject)=>{worker.onmessage=e=>{if(['done','error'].includes(e.data.type)){worker.terminate();e.data.type==='done'?resolve(e.data.state):reject(Error(e.data.message));}};worker.onerror=e=>{worker.terminate();reject(Error(e.message));};});worker.postMessage({state:structuredClone(s),steps:40});
  for(let i=0;i<40;i++){if(direct.pending||direct.retired||direct.match||sport.hasSportPause(direct)||sim.destinationReached(direct))break;engine.next(direct,{interactive:false,untilDay:direct.day+1});}sim.settleAdvance(direct);
  const remote=await output,workerIdentical=JSON.stringify(remote)===JSON.stringify(direct),cursor=JSON.stringify(s.simulation.cursor);let decisions=0,steps=0;
  while(s.day<80&&steps++<1200){if(sport.hasSportPause(s))sport.acknowledgeSport(s);else if(s.pending){decisions++;if(s.pending.type==='contract')engine.sign(s,0);else engine.decide(s,s.pending.type==='draft-choice'?'draft':s.pending.type==='offseason'?'shoot':s.pending.choices[0][0]);}else engine.next(s,{interactive:false,untilDay:s.day+1});if(s.simulation.mode!=='40'||JSON.stringify(s.simulation.cursor)!==cursor)throw Error('Destination perdue');}
  engine.validate(s);const retired=structuredClone(s);collective.bookStage(retired,collective.stageQuote(retired,'video'));commands.retireCareer(retired);if(retired.collective.stage)throw Error('Stage non clos après retraite');
  return {workerIdentical,decisions,day:s.day,paid:s.collective.totals.paid,sessions:s.collective.totals.sessions,closed:s.collective.history.length,mode:s.simulation.mode,target:s.simulation.cursor.targetSeason,retirementClosed:true};
 },VERSION);
 assert.equal(simulation.workerIdentical,true);assert.ok(simulation.decisions>0);assert.equal(simulation.day,80);assert.equal(simulation.closed,1);assert.equal(simulation.mode,'40');assert.equal(simulation.target,2);assert.deepEqual(errors,[]);
 const fingerprint=crypto.createHash('sha256').update(['app','v38-view','collective','collective-state','collective-match','engine','config'].map(n=>fs.readFileSync('dist/'+n+'.js','utf8')).join('')).digest('hex');const result={engine:VERSION,fingerprint,seeds:[2026],errors,widths:[320,390,1440],routineAndPartners:true,quoteCancel:true,staleQuoteReconfirmation:true,singlePayment:true,workerSession:true,focus:true,reload:true,offline:true,importClearsQuote:true,simulation,physicalSafari:false};fs.writeFileSync('tests/v38-browser-report.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();await new Promise(r=>server.close(r));}
